### ISSUE TITLE
Login for comments fails

### ISSUE THREAD

**Issue by CodingBobby** [croqaz/crlf#1]
Signing in to write a comment under a post only seems to work for the Google option (and I don't want to login with Google).
Both GitHub and Twitter throw an error.

When clicking the GitHub option, I get redirected to `https://comment.crlf.link/auth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application...` which shows this error:
```json
{"error":"exchange failed"}
```

For Twitter I reach `https://comment.crlf.link/auth/twitter/login?from=...` and it shows:
```json
{"error":"failed to get request token"}
```

In the same browser, I am already logged into GitHub and Twitter but the errors still appear when I logout on the sites.

**Comment by croqaz** [comment]
You're right, it was broken because the auth URL was http:// instead of https://
I updated both of them now and I tested, it works.
Sorry :)
Thanks for letting me know!
